// Isolated browser fixture: no account, inventory or marketplace writes.
const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const assets=path.resolve('src/main/resources/static');
http.createServer((req,res)=>{
  const url=new URL(req.url,'http://localhost');
  if(/^\/(css|js)\/[a-z0-9-]+\.(css|js)$/.test(url.pathname)){
    const file=path.join(assets,url.pathname);if(!fs.existsSync(file)){res.writeHead(404).end();return}
    res.setHeader('Content-Type',url.pathname.endsWith('.js')?'text/javascript; charset=utf-8':'text/css; charset=utf-8');res.end(fs.readFileSync(file));return;
  }
  const mode=url.searchParams.get('mode')||'local',size=Number(url.searchParams.get('size'))||25,page=Number(url.searchParams.get('page'))||0;
  const chat='<button class="collaboration-row-button" data-entity-type="ORDER" data-entity-id="test" data-active-count="2" data-total-count="2" aria-label="Open conversation"><svg viewBox="0 0 24 24"><path d="M5 5h14v9H9l-4 4Z"/></svg><b>2</b></button>';
  const count=mode==='server'?Math.min(size,61-page*size):61;
  const rows=Array.from({length:count},(_,i)=>'<tr><td>Product '+(i+page*size)+'</td><td>'+(i%2?'West':'East')+'</td><td><strong class="weekly-sales">3 | 0 | 10 | 2</strong></td><td>'+chat+'<button>Edit</button></td></tr>').join('');
  const grid=Array.from({length:25},(_,i)=>'<article class="order-row"><div class="order-items"><div class="order-item"><div class="item-product">Product '+i+'</div><div class="item-order-reference">Order '+i+'</div>'+Array.from({length:5},()=>'<div class="item-number">12</div>').join('')+'<div class="item-map">Mapped SKU</div><div class="item-actions"><button>Ship</button></div></div></div><div class="order-actions">'+chat+'<span class="shortage-message"><span>Mapped · waiting for sellable inventory</span><button onclick="document.querySelector(\'#action-result\').textContent=\'Correct order: \'+this.closest(\'.order-row\').querySelector(\'.item-order-reference\').textContent">Adjust stock</button></span></div></article>').join('');
  const pager=mode==='server'?'<div class="table-footer table-pagination"><span>Showing rows</span><nav><form data-page-jump><input name="goToPage" value="'+(page+1)+'" data-page-max="'+Math.ceil(61/size)+'"></form>'+(page+1<Math.ceil(61/size)?'<a href="?mode=server&page='+(page+1)+'&size='+size+'">Next</a><a href="?mode=server&page='+(Math.ceil(61/size)-1)+'&size='+size+'">Last</a>':'')+'</nav></div>':'';
  res.setHeader('Content-Type','text/html; charset=utf-8');res.end('<!doctype html><html data-theme="'+(url.searchParams.get('theme')==='dark'?'dark':'light')+'"><head><meta name="viewport" content="width=device-width,initial-scale=1">'+['app','brand','order-stream','collaboration-chat','collaboration-smart','collaboration-thread','table-widget','background-jobs'].map(name=>'<link rel="stylesheet" href="/css/'+name+'.css">').join('')+'<style>body{padding:30px;display:block}main{max-width:1400px;margin:auto}.after-table{height:700px}</style></head><body><main><h1>Table standards · isolated test</h1><section class="data-card">'+(mode==='grid'?'<div class="order-list table-widget-scroll" data-table-widget="orders"><div class="table-grid-header order-item-grid-header">'+['product','order','quantity','sales','buy-box','shipping','available','catalogue','action'].map(id=>'<span data-column="'+id+'">'+id+'</span>').join('')+'</div>'+grid+'</div>':'<div class="table-wrap"><table data-table-widget="fixture"><thead><tr><th>Product</th><th>Location</th><th>4w sales</th><th>Action</th></tr></thead><tbody>'+rows+'</tbody></table></div>')+pager+'</section><p id="action-result"></p><div class="after-table">Page continues below table</div></main>'+['table-preferences','table-widget','table-data-tools','background-jobs'].map(name=>'<script src="/js/'+name+'.js"></script>').join('')+'</body></html>');
}).listen(18083,'127.0.0.1',()=>console.log('Table fixture: http://localhost:18083'));
