package com.nextaicommerce.platform.orders;
import static org.assertj.core.api.Assertions.*;
import java.util.Map;
import org.junit.jupiter.api.Test;
class OrderSmartFiltersTest {
 @Test void smartDatesMoveWithTimeAndRespectMarketplaceMidnight(){var zone=java.time.ZoneId.of("America/Los_Angeles");var clock=java.time.Clock.fixed(java.time.Instant.parse("2026-09-20T02:00:00Z"),zone);var q=OrderSmartFilters.parse(Map.of("f_date_preset","today"),zone,clock);assertThat(q.args()).containsExactly(java.time.OffsetDateTime.parse("2026-09-19T00:00:00-07:00"),java.time.OffsetDateTime.parse("2026-09-20T00:00:00-07:00"));assertThat(q.sql()).contains("purchase_date<?");var next=OrderSmartFilters.parse(Map.of("f_date_preset","today"),zone,java.time.Clock.offset(clock,java.time.Duration.ofDays(1)));assertThat(next.args()).doesNotContain(q.args().getFirst());}
 @Test void previousCalendarPeriodAndOffsets(){var clock=java.time.Clock.fixed(java.time.Instant.parse("2026-09-19T12:00:00Z"),java.time.ZoneOffset.UTC);var q=OrderSmartFilters.parse(Map.of("f_date_preset","last_month","f_date_end_offset","2"),java.time.ZoneOffset.UTC,clock);assertThat(q.args()).containsExactly(java.time.OffsetDateTime.parse("2026-08-01T00:00:00Z"),java.time.OffsetDateTime.parse("2026-09-03T00:00:00Z"));assertThatIllegalArgumentException().isThrownBy(()->OrderSmartFilters.parse(Map.of("f_date_preset","today","f_date_start_offset","2")));}
 @Test void channelsUseAmazonDatabaseValues(){var q=OrderSmartFilters.parse(Map.of("f_channel","FBA"));assertThat(q.args()).containsExactly("FBA","AFN");assertThatIllegalArgumentException().isThrownBy(()->OrderSmartFilters.parse(Map.of("f_channel","invalid")));}
 @Test void otherCalendarPresets(){var clock=java.time.Clock.fixed(java.time.Instant.parse("2026-09-19T12:00:00Z"),java.time.ZoneOffset.UTC);for(var pair:Map.of("yesterday","2026-09-18T00:00:00Z","last_week","2026-09-07T00:00:00Z","last_year","2025-01-01T00:00:00Z").entrySet())assertThat(OrderSmartFilters.parse(Map.of("f_date_preset",pair.getKey()),java.time.ZoneOffset.UTC,clock).args().getFirst()).isEqualTo(java.time.OffsetDateTime.parse(pair.getValue()));}
 @Test void valuesStayBoundAndWildcardsAreLiteral(){var q=OrderSmartFilters.parse(Map.of("f_sku","x%' OR 1=1 --"));assertThat(q.sql()).doesNotContain("OR 1=1");assertThat(q.args()).contains("%x!%' OR 1=1 --%");}
 @Test void rangesAreInclusive(){var q=OrderSmartFilters.parse(Map.of("f_quantity_min","2","f_quantity_max","8"));assertThat(q.sql()).contains(">=?","<=?");assertThat(q.args()).hasSize(2);}
 @Test void rejectsReversedRangesAndUnknownSort(){assertThatIllegalArgumentException().isThrownBy(()->OrderSmartFilters.parse(Map.of("f_sales_min","9","f_sales_max","2")));assertThatIllegalArgumentException().isThrownBy(()->OrderSmartFilters.parse(Map.of("smartSort","drop table")));assertThatIllegalArgumentException().isThrownBy(()->OrderSmartFilters.parse(Map.of("f_date_min","2026-09-20T00:00:00Z","f_date_max","2026-09-19T00:00:00Z")));}
}
